### ISSUE TITLE
Support Takeout.zip-s from Google Photos

### ISSUE THREAD

**Issue by im7mortal** [ente-io/bada-frame#243]
Do you have an API documentation?
I would like to export my Google Takeout zip archive in ente.

**Comment by abhinavkgrd** [comment]
you can just unzip the archives you've downloaded from Google, and drag and drop the folders to web.ente.io.

ente parses the metadata generated by Google, encrypts them along with your files and backs all of them up to our servers.

**Comment by im7mortal** [comment]
@abhinavkgrd Thank you for fast response!

It's not going to work. :no_entry_sign:

My archive contains 30GB and around 1000 directories. Something around 10000 files. 
And I have small Takeout zip. I know people who have much bigger data. 
Nobody will want to import thousands directories manually and wait 12 hours. Also there are much more errors during web uploading of many files.

I like to hear though you keep metadata of photos during migration. 

Do your Desktop app support Takeout.zips? or it supports already extracted data? 

It would nice it could look for `Google Photos` in the Takeout.zip and then parse data and upload everything parallely

**Comment by vishnukvmd** [comment]
Hey @im7mortal thanks for the feedback. I've added this to our [roadmap](https://roadmap.ente.io/process-google-photos-takeoutzips-p-3662/) and taken the liberty to add an upvote on your behalf.

Currently, you could unzip all of the `Takeout.zip`s, and drag and drop all of the resulting folders into our desktop/web app. During this process if you choose the option to create separate albums per folder, we will identify and merge albums with the same names together, preserving your album structure across all of these takeouts. And even if the upload breaks, you just have to drag and drop these folders again, we'll skip through the duplicates.

I hope for the time being this will help. We'll update this issue once we've added support for parsing `Takeout.zip`s directly.

**Comment by im7mortal** [comment]
So I tried to use web upload. 
I had 25GB and 9800+ files
It loaded around 7000 for 12 hours then I closed it.

How do you compare that file is the same? do you get hash sum? because I saw message that it skips files because they **have the same name**
Btw zips already have _CRC32_ hash calculated for the validation

**Comment by vishnukvmd** [comment]
Correct me if I'm wrong @abhinavkgrd, but I believe we ignore files with the same name that have been uploaded to albums with the same name.

**Comment by vishnukvmd** [comment]
Sorry to hear that Petr!

To purge data, you can hover over an album name, click on the "three dots" that pops up, and then click on "delete". 

Circling back to the memory leak, could you please let us know what browser you were on? Thanks!

**Comment by im7mortal** [comment]
![Captura de pantalla de 2021-12-15 13-37-49](https://user-images.githubusercontent.com/5336231/146245562-defd1c52-a775-4a45-a19e-f639fdfd8073.png)


I will try  to purge data and resync it later

**Comment by im7mortal** [comment]
Maybe you could open API documentation? 
I've never did it again. I have a new laptop with 160GB (I especially have small disk to remember to keep only essential data locally) . I already have 25GB zip on the drive and I don't want to unpack all photos locally. 
From other hand I don't want to repeat all process of manual syncing through web page. I tried it so many times.

**Comment by vishnukvmd** [comment]
@im7mortal Hey! We are working on adding the ability to "watch" a folder from the desktop app. This will help us retry failed uploads without manual intervention.

Coming to zip files, unfortunately, we will have to unzip them to disk to process them. The reason is that Google strips some EXIF metadata from photos and maintains them separately (`file-name.json`). Our uploader currently matches the photos with their corresponding metadata files and parses the latter to not lose any information.

"Seeking" through a zip file will not allow for this. :(

**Comment by im7mortal** [comment]
It's not necessary to unzip files. 


ZIP keep headers and body separate. 

![imagen](https://user-images.githubusercontent.com/5336231/154849351-b867e445-c09e-49f5-85eb-1e02421f9123.png)

It's possible to iterate over headers and match corresponding `.json` metadata with actual photos. 

![Captura de pantalla de 2022-02-20 10-07-31](https://user-images.githubusercontent.com/5336231/154849257-69c905dc-25b3-48fc-b6cc-e0e25c6170e3.png)

It's going to be only one open fie descriptor. I am not sure if Javascript supports WriteAt on bytes buffers. Should be.

**Comment by vishnukvmd** [comment]
This is great! Sorry for making the wrong assumption, and thank you for sharing this! We should be able to get this to work on the desktop.

We are currently tied up in getting a beta release of our desktop app out with face, object, and text detection. Once we've done that, we will get to this.

**Comment by vishnukvmd** [comment]
Hey @im7mortal! We've shipped the following improvements to our desktop app:

- Ability to parse `Takeout.zip`s exported from Google Photos
- Ability to resume uploads on app/system restart

<img width="406" alt="Screenshot 2022-04-26 at 4 47 41 PM" src="https://user-images.githubusercontent.com/1161789/165289372-15953b4d-cfed-409b-a70c-922dac25b13e.png">

If your app doesn't auto-update, please grab the latest release from here: https://github.com/ente-io/bhari-frame/releases/latest

Thank you for this suggestion! If you run into any issues, please reopen this issue or create a new one! 😊

**Comment by im7mortal** [comment]
@vishnukvmd  It's much more faster now now. Good job!

I tried 2 times run it overnight. At some moment it give me this error.

![Captura de pantalla de 2022-05-14 07-20-09](https://user-images.githubusercontent.com/5336231/168472821-88968be6-0bbc-44a1-bfd9-19f469aaf2f7.png)

I can't give you details as it prints nothing in terminal.

1. I would request you add in interface option `about` so it would be possible to figure out which version we use. Maybe also `--version` flag.

2. Maybe `--verbose` flag could help there? or it could write error to some local log file

**Comment by abhinavkgrd** [comment]
Hey @im7mortal, we've added additional logging to better understand what could be going wrong. Could you please try to reproduce the issue and click on "debug logs" from the sidebar and email the generated log file to support@ente.io? We'll get back to you asap!
