### ISSUE TITLE
Web version doesn't work in incognito

### ISSUE THREAD

**Issue by im7mortal** [ente-io/bada-frame#251]
**Firefox 94.0.2 (64-bit)**

It's not possible to use ente in incognito. I consider that it should be possible to use end-to-end service without leaving traces

![Captura de pantalla de 2021-11-25 10-09-15](https://user-images.githubusercontent.com/5336231/143486674-9f58e0a4-646d-46c3-a604-b129c1dfd208.png)

**Comment by vishnukvmd** [comment]
@abhinavkgrd Shall we write an in-memory wrapper over localForage?

**Comment by abhinavkgrd** [comment]
Hii @im7mortal ...So we have shipped the ability to use ente in incognito mode in our latest release 😄
- #328 
please let us know if u  face any issues using it.

**Comment by im7mortal** [comment]
Thank you  @abhinavkgrd ! 
I tested it from incognito Firefox all worked well
