### ISSUE TITLE
Map feature did not work with some coordinates

### ISSUE THREAD

**Issue by MalteKiefer** [ente-io/bada-frame#661]
Hello,

on some photos, the "Show Map" feature is not working.
I send you two screens, one where you see the missing link and one where you see the full EXIF data with GPS coordinates:
![image](https://user-images.githubusercontent.com/59220985/179741230-84f65e5d-5e5c-4b24-a0ae-36bb5592fe21.png)
![image](https://user-images.githubusercontent.com/59220985/179741242-cc0341fe-375e-4151-8767-403e5a92d262.png)

**Comment by abhinavkgrd** [comment]
Hii @MalteKiefer, we have released the fix for it, if you are still facing the issue, feel free to reopen the issue
